# Generated by Django 5.0.14 on 2026-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupée'), ('RESERVED', 'Réservée'), ('TO_CLEAN', 'À nettoyer'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
