# Generated by Django 5.0.14 on 2026-10-11 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_cashsession_closed_at_cashsession_closing_amount_and_more'),
        ('finance', '0002_expense_tax_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashier.cashsession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice'),
        ),
    ]
