# Generated by Django 5.0.14 on 2026-09-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0002_room_floor_room_nightly_rate_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room'),
        ),
    ]
