# Generated by Django 5.0.14 on 2026-09-17 01:17

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('role', models.CharField(choices=[('ADMIN', '1. Administrateur Système'), ('DIRECTOR', '2. Directeur / Gérant'), ('RECEPTIONIST', '3. Réceptionniste'), ('BOOKING_AGENT', '4. Agent de Réservation'), ('HOUSEKEEPING_MGR', '5. Responsable Housekeeping'), ('HOUSEKEEPER', '6. Femme / Valet de Chambre'), ('MAINTENANCE_MGR', '7. Responsable Maintenance'), ('TECHNICIAN', '8. Technicien Maintenance'), ('ACCOUNTANT', '9. Comptable'), ('CASHIER', '10. Caissier'), ('RESTAURANT_MGR', '11. Responsable Restaurant'), ('WAITER', '12. Serveur'), ('KITCHEN_MGR', '13. Chef Cuisine'), ('COOK', '14. Cuisinier'), ('STOREKEEPER', '15. Magasinier'), ('HR_MGR', '16. Responsable RH'), ('COMMERCIAL_MGR', '17. Responsable Commercial'), ('NIGHT_AUDITOR', '18. Night Auditor (Clôture)')], default='RECEPTIONIST', max_length=30, verbose_name='Rôle Système')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département / Service')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité Utilisateur',
                'verbose_name_plural': 'Activités Utilisateurs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
