# Generated by Django 5.0.14 on 2026-10-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_role',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '1. Administrateur Système'), ('DIRECTOR', '2. Directeur / Gérant'), ('RECEPTIONIST', 'Réceptionniste'), ('HOUSEKEEPING_MGR', '5. Responsable Housekeeping'), ('HOUSEKEEPER', '6. Femme / Valet de Chambre'), ('MAINTENANCE_MGR', '7. Responsable Maintenance'), ('TECHNICIAN', '8. Technicien Maintenance'), ('RESTAURANT_MGR', '11. Responsable Restaurant'), ('WAITER', '12. Serveur'), ('KITCHEN_MGR', '13. Chef Cuisine'), ('COOK', '14. Cuisinier'), ('STOREKEEPER', '15. Magasinier'), ('HR_MGR', '16. Responsable RH'), ('COMMERCIAL_MGR', '17. Responsable Commercial'), ('NIGHT_AUDITOR', '18. Night Auditor (Clôture)')], default='RECEPTIONIST', max_length=30, verbose_name='Rôle Système'),
        ),
    ]
