# Generated by Django 5.0.14 on 2026-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('alert_level', models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critique'), ('OUT_OF_STOCK', 'Rupture')], default='NORMAL', max_length=20)),
            ],
        ),
    ]
