# Generated by Django 5.0.14 on 2026-10-11 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
        ('reservations', '0002_reservation_guest_reservation_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_in_record', to='reservations.reservation'),
        ),
    ]
