# Generated by Django 5.0.14 on 2026-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
